type: data
name: Config
label: Site configuration
singleInstance: true
readOnly: true
fieldGroups:
  - name: seo
    label: Site SEO configuration
fields:
  - type: image
    name: favicon
    label: Favicon
    default: 'https://assets.stackbit.com/components/images/default/favicon.svg'
  - type: model
    name: header
    label: Header configuration
    models: [Header]
  - type: model
    name: footer
    label: Footer configuration
    models: [Footer]
  - type: model
    name: seo
    label: SEO
    models: [SeoSite]
